language: java

jdk:
  - openjdk18

# Need a full git clone in order to be able to tag the release
git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
  - gpg --fast-import .travis/gpg.asc

env:
  global:
    # Environment variables referenced in .travis/maven-settings.xml. To encrypt and escape values correctly, run the following
    # command and enter ENV_VAR=value when prompted:
    # read -r && travis encrypt "$(printf %q "$REPLY")"
    - secure: rsRxCN87eU1b43kcPkaAMxF4gEvSl3+dthoNGtmjD53ID7BTooopykUAsP4sMOc62fwSDiUMeqbTc4hNgmFvsJK8z7hMzHQRjNlza0Yy/JCzgbEAQrvYUtyIaEd/3OM27nQYkypGhc/w90+aWGxPQNoLRHrBMzI85Fh/9qLq4eISQCjskNZ3CWRfCJsPb9h11pnjVhwYoCXm6gUcyKmgui7l76d1AC4pUfIB0BCCrIY07+uf5zhYD5fJ3VyBIQodgp2PhpDUoFE5W9J8mNdBEmMylEwja1M2RkTCnHUyyFv1AOj5y9DsnFUQmJn/tJFpqpZ4nbeMSjYnhzEIs+1w5DptsaYATuAoPvH4q5Xrj8fPaDRtiGt+rMdUHiq+8z8R3DurHKGfxq/nFVMEwJJV51gvURBsmlvRRPlh/i/cLp/L8+/vEzkb++uMChZ8wOvQSqiFMS+Mje3h+o4/YYQKQuPiloRv5K8mixnXFpKl5QNVKexgle65bXRONnonR+j+7RfETRa+QlwJHosQ5GqL0IPIw/RjPJyZw5pnD4G9jaGlMGkfpmOytjUH4+cRvprz8ZyrZB66MsFzYh+C2oCVJfOg1xcCeVwQ26/mV4L74So4/6dYQeFmgfz0HZ8Ne1FMGFf+PiMyoNIrz7SXlvClPsmpACO9/qfCjmzM/Y+FCZU=
    - secure: rqTZmjnMCTePJgC6quR3eefI8oOQ3e6xhgsP74oamWvQcAXdEVBz1w66rr6SQ86W2oqDsKfl6r+XBwDDE7aOmFSAvu0VYUvxy0JQ6k3bGeMOrmH+ocueCKRY072zVThaBkba84VSpFzXryYIa8ziL1GffZLEYT05H/MUylU3qClxmQdfTtNnA/FGIc2n1JMxqG+mW79XvQuIPljLL6vL9QE1YRn7TZMjjHkeyfaYK4QMSLqA8fO5wuz7HQ2SQzoEk89gMLvFQf5XTjg5nAziSy6q88sq463x4/wohKXz9hse2+jTNZfRBCVDdPPg++3hNzBTvIPq16WWiA8i/IW+TesM0UMpuDqfm4PTaDp3+4YqMrL1emEvbTJKcBnFC55zMElRG80VK8M6C192hTPq/dRIxcsgD797Hzb1c3V7m5QjNARdyweyfpEU0oC+MgdUrsXgqcOjNiJdlcn1E9TeLSIMN7gU7YsP1WhrQOefsbSnDaKsmR3HzXuTHWJqSszrfa2hjzweTeLxB3yJ4j548+fhZQbGnyA2dqqUiQ9mhQqumqRfaihsqJHRd4Cuk4u+vki/b1bngOrEvZZgp3QEpn9O4TfWa9XsDyCMaJ/7B5pR7/UvtB0pHfTQf7Gmv5I5N8chi4Y403n/kJZNPrvmB0bxGpzvMxleKFLYHBtt5Vc=
    - secure: dVJ0/t/5bJA4i3JCLJxCeLNnLzsAtS+9sY1+DhNtEN441wrmRAdbT2B3TPQN0kb9dz4ShDR6XG5gdrNzxPvjXHD4N3GtjC54cB82/CDcYeB/bP08NegdE4d0tZUZUONtartOJ0SLRDLyZskaFWVa84AWvqJDfjfjcKPqur/c0C+Hu4tyO1j4fHrsroPZ/qTg9Y9tYmhWP6Nl43LMEGH2xqcG0ieTi6gew4OUbXhaGJOWsvGX6UCNb7lPxFYAqdKDbg4w6L55B1qYgG9KJZ3NkjiFa+saxQLwza5+issX991DNd/xlnQm2pLbPCHqfK058AQ+4PscEuJmQWhfygWWmZbHbrwBVYIMQ55nDngckzO1UAWFhM/HkGc0S8UNpZ67X95MWOo7IQ6amKmNP2/OWb0LZXD0heMCNIGArpSMPMGliN6HcMLjAYV4R010VqF0G+ugobSKpq2WqccSr1JSHMAUKU0sEXlk9nyndGbkTZvC+SAGSCxUdJYPxrkeUcOVvsxck8k3Jb5XJxSx9Uzou4W1wzMrldQDK51uex/gcjYOxueyHhx+nmW/XZCoEdJfKsJmMOzpTvCVGTU1+wedhfey9r2YBq+LrDDyD7YKnQWY+d/WMFAphOQQeDFwYXKEoUxQB4zI/qSBGjA/CH4bmth9clayPHDCzGcw8wruyDg=
    - secure: ozTTdjnPK3BohbEEaiSOxUPWhDO/GV3eSXKqItB+YHF9/b5bSFJ1e7CmLOgJPPzg32ys9tXDt71NLv2C0SWw5u/8xV5/BaU/EX7LhlCvzqzugeGpl3MD49Srz2dfl7b3yiL6K24GkKUWfBlWuf9o8R8O7YqOxF23jYMKawFL8BkJtWtu5W0BwGabsgtUTHW8ZTE+5hrZ7u32UicSdlzaaFXVW6QcAYvfGW2IVyITncgEu1oXKMIsuLta284sJ1pSbGzKxiKJ9y12CLVVN2c+W/gLWBALmg76kwV9KiO7Bn4g7rHCqbzXfnJpNjgG5HMlnsr7ChotmLJzYUSLhkiNivfnaGPp1yqqeHGtmjEp7G3Zv3yzZhvhrsb1aINhOElF/+qONMzv5X4DuWdl9+fUJSTnWfxKZ2j7iQ2LVgc55LpEidNUiYAwFMNE0ZNaqTL420OsIKyeRDzAJsirSFflwaxEBR3TS/4Cve+o/VmzQF3HfWAuR5OEd5BYdjo3Sa9X7thqRGtPNPTVJJ777Tyabszm/7iElcrBCA2DyDLa853ohinUkgn03OwMwRhgx3vWr0jx7JXlTsZprcheeJgx/qkKtdbMff4d9HM+qox6zn4OO3au0ZhWwyXSeietDLO5hEJoc1BNTM+aA0Fe91v4qq8UbNlM6Zt1/Nd+0VO6RwY=
    - secure: xKbBdYjtcduhU76JOBHYpb6gAb0XJWi69o8+igLpU9iYz8wOljL06Z9UW0d4U3mgTah+QPBawZcKnFNMeUDy+B7ShLRh3C4hnOkUIxNv7IRQ7S+OGbF62EzS9CNyc5A1Rv1zBP9dXnmfyJq/F0Lta/Gi+ftp5ND3FEaFbvuSCCBC70i8Q2Xp9S1gPzyY2ByibAEjMm/Nu9rxKpx5Xs1D/JLqaVCA8PryGl3AbMAA7vAoY2s4/parvtaZNaE9GZBy2hxEom0/1dZiJ2/dTaQUk8gLMZ9NU1zuXfMcYU8b8GsBl1GvFwOTP8qGWDXkTSZ5itZDRTeIHfCNLCBS+XOv3RXQCxLiGhoreCHATXodEpEf6Nj/xtd5JmyV0MURgYtayk4G6dnq5cilXwZ2cY+RfCbw6nmPW7WZwNqhRyPTIhWVYpsvKbyCbpeWujGduUCjKuvekfTCiXRfvwfu6cIlyWXhoJZfgLCXeOm4pwNrMpE0rTF+6au6ZXTSDlmlpDqUTI50u8nTr9fIK/+DBu1d4350zZ1Q5qP2VRrDv68JueYJrPNOfSdlUW6gRi0SpWGvxcyK6JBRnw2o7aCl7HgO9CSnJ7lNqsl7iVJTZdbXkIiPoVmBtNcZpX8iE/0nxrTEjhpzz+SHJiSurQaFsNXlyVvKF2yyfTIGOsZMaAkiqJc=

script:
  - mvn clean install -B
  - mvn org.pitest:pitest-maven:mutationCoverage -B

before_deploy:
  # Set tag to be used by releases provider
  - export TRAVIS_TAG=$POM_VERSION

deploy:
  # For any checkin to main branch, create a final version, tag it and push the artifacts to Sonatype
  - provider: script
    skip_cleanup: true
    script:
      mvn --settings .travis/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
    on:
      branch: main

  # Releases config copied from https://docs.travis-ci.com/user/deployment/releases/ and secure key generated by following
  # https://stackoverflow.com/questions/25302518/travis-ci-setup-releases-with-github-token#answer-57032190
  - provider: releases
    api_key:
      secure: NUJjBX9TCNIgsT1fLOQTHrkflMos6ZLSa9Y1S55EaFlxQt2Rkl1NJOYSRLyKipehUifhNV/81nZInH5d6svBa8ag60uwK1xuaVirPI8VFsomKxDavQWpiDBISYr4oo/HqDzoBRM6QzvmETBf1xzBBJjO+9GIIpE4DiBUC8FzvyOIhMwVrMvTB6sjW4biF+cicDjvWP3Xo9R7OWyZ0dOYqoWfCHyViG39kithXFJa2bZwcoxsC2ViIrUGVTfsg9hrON+EKGrHxM89GV4VjqDodomMlXgmRSKL941BCpANInTGbSPS+QAhRjH0pKbml239bQLMF1kdAXJUELm2Ropn27fYdJxJjK+QdibudL1YasrNhcYxAfWRRK/dXE7/2LpoYu7mjUfMvWzEuOWojDrbSzitL/0M/1++vSveuZEDAjNV1UYk/Wxr4iO0U1xat6RU+iLzW1gqXsfIAQun1xaGmyeMsYY5NBCky6hBvpdlXhVgSjqGOu+EMt3mdrI/XCMmOp3QagjXGSZlMG9Fp94HmodSH3M6YQ0Kbvmm/58kI2r3xc3xPzYcDLsz4wYkAeEPe1Ik9zZi+dcxWwhUfr/3eGEMRRrITjy01Y9oC6YOcGUnc/lLUDRRaggcS77XNYQ/WDY105psJ0c53i0GrFzZHed3jeDeubrjLBdnNjKRm2s=
    file:
      - "spt-development-logging-spring-boot-autoconfigure/target/spt-development-logging-spring-boot-autoconfigure-${POM_VERSION}.jar"
      - "spt-development-logging-spring-boot-starter/target/spt-development-logging-spring-boot-starter-${POM_VERSION}.jar"
    skip_cleanup: true
    on:
      branch: main
